### PR TITLE
fix: rework pointers/references between Player and Level

### LINKED ISSUE #44: Memoryleak in shared_ptr<GameLogic::Level>
De smartpointer naar level heeft waarschijnlijk een dubbele reference.

level_memleak

### PR DESCRIPTION
**Pull request by ThomasvLingen**
Before, there was a circular shared_ptr, causing a memory leak. Now,
Player is a reference of Level instead.

This commit closes #44

### CODE REVIEW

File: src/gamelogic/Game.hpp [hunk 1]
```diff
@@ -43,7 +45,7 @@ namespace GameLogic {
         SPTR_IGameState _new_state;
 
         SPTR_Level _level;
-
+        std::shared_ptr<Player> _player;
```
Comment (jorgdebont) [inline src/gamelogic/Game.hpp]: plz define a typedef for this
